### ISSUE TITLE
request entity too large error

### ISSUE THREAD

**Issue by sheerun** [gja/cloudflare-worker-local#31]
I'm sending 4.6MB POST request which should be fine size for cloudflare workers, but it results with following error when testing locally:

```
[0] PayloadTooLargeError: request entity too large
[0]     at readStream (/Users/sheerun/Source/.../api/node_modules/raw-body/index.js:155:17)
[0]     at getRawBody (/Users/sheerun/Source/.../api/node_modules/raw-body/index.js:108:12)
[0]     at read (/Users/sheerun/Source/.../api/node_modules/body-parser/lib/read.js:77:3)
[0]     at rawParser (/Users/sheerun/Source/.../api/node_modules/body-parser/lib/types/raw.js:81:5)
[0]     at Layer.handle [as handle_request] (/Users/sheerun/Source/.../api/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/sheerun/Source/.../api/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/sheerun/Source/.../api/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/sheerun/Source/.../api/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/sheerun/Source/.../api/node_modules/express/lib/router/index.js:275:10)
[0]     at expressInit (/Users/sheerun/Source/.../api/node_modules/express/lib/middleware/init.js:40:5)
```

Could you set better limits for body parser?

**Comment by sheerun** [comment]
I think default limit of bodyParser is 100kb which is way too low

**Comment by gja** [comment]
Hi. Thanks for the issue. Would you mind sending this as a pr as well? Else I’ll look at this over the weekend. I’d say removing the limit would probably be the least surprising.

**Comment by sheerun** [comment]
Sure I've sent PR
