### ISSUE TITLE
does not support ES module worker

### ISSUE THREAD

**Issue by wighawag** [gja/cloudflare-worker-local#78]
Error:

```
SyntaxError: Unexpected token 'export'
    at new Script (vm.js:102:7)
    at Worker.evaluateWorkerContents (/home/wighawag/dev/wighawag/etherplay/conquest-agent-service/node_modules/cloudflare-worker-local/app/worker.js:111:20)
```

**Comment by gja** [comment]
Hi @wighawag . Sorry for the late response, and thanks for the bug. I guess as it stands, since this is built on node, which doesn't support ES modules, I don't think this will work out of the box. Please use babel in the meanwhile.
