### ISSUE TITLE
Getting error while running google index script

### ISSUE THREAD

**Issue by rsoorajs** [gja/cloudflare-worker-local#91]
Getting this error while running google index script `TypeError: Cannot read property 'asn' of undefined` 

https://gitlab.com/GoogleDriveIndex/Google-Drive-Index

the issue is while running the below generated .js file. You can regenerate this issue using below link. kindly fix it thank you

https://bdi-generator.hashhackers.com/

**Comment by rsoorajs** [comment]
```

2022-07-14T14:12:45.963585332Z at async FetchEvent.__response (/usr/local/lib/node_modules/cloudflare-worker-local/app/worker.js:57:35)
2022-07-14T14:12:45.963615385Z at async Worker.executeFetchEvent (/usr/local/lib/node_modules/cloudflare-worker-local/app/worker.js:151:14)
2022-07-14T14:12:45.963625647Z at async callWorker (/usr/local/lib/node_modules/cloudflare-worker-local/app/server.js:12:20)
2022-07-14T14:12:45.963634528Z at async /usr/local/lib/node_modules/cloudflare-worker-local/app/server.js:53:7
2022-07-14T14:12:46.757529443Z TypeError: Cannot read property 'asn' of undefined
2022-07-14T14:12:46.758107326Z at handleRequest (evalmachine.<anonymous>:854:36)
2022-07-14T14:12:46.758122981Z at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-07-14T14:12:46.758129394Z at async Promise.all (index 0)
```

**Comment by gja** [comment]
Hi @rsoorajs,

Thanks for the bug report. Could you share a simple script that reproduces the bug? This looks like a web pack related issue. 

Tejas
